/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacePanel;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.util.Stack;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import testmaze.*;
/**
 *
 * @author Sirijus
 */
public class Interface extends javax.swing.JFrame {
    int saveCount = 0;
    int ilgiausioid=0;
    public Labirintas test=null;
    public Langelis dabartinis = null;
    boolean checkCells = false;
    public boolean [] langeliai  = null; // visi
    public Langelis [] gretimi  = null; // esamo langelio gretimi langeliai 
    public boolean [] gretimuReiksmes  = null; // esamo langelio reiksmes i gretimus langelius
    public boolean [] nepraeiti  = null;
    public int nepraeitiCount =0;
    int id=0;
    int xxx = 0;
    Stack<Integer> stack = null;
    Taskas taskas = null;
    int matmuox = 10;
    int matmuoy = 10;
    public boolean motionTrack = false;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        output = new interfacePanel.LabirintasPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(560, 165));
        jDialog1.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Žaidimas pereitas");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 900));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        output.setBackground(java.awt.Color.white);
        output.setAutoscrolls(true);
        output.setMinimumSize(new java.awt.Dimension(700, 780));
        output.setName("output"); // NOI18N
        output.setPreferredSize(new java.awt.Dimension(700, 780));
        output.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                outputMouseDragged(evt);
            }
        });
        output.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                outputMousePressed(evt);
            }
        });
        output.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                outputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout outputLayout = new javax.swing.GroupLayout(output);
        output.setLayout(outputLayout);
        outputLayout.setHorizontalGroup(
            outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outputLayout.setVerticalGroup(
            outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("10");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Height ( From 1 to 24 )");

        jLabel2.setText("Width ( From 1 to 24 )");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("10");
        jTextField2.setToolTipText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        test=null;
        int tempox=Integer.parseInt(jTextField1.getText());
        if(tempox>1 && tempox<25){
            //if(tempox%2==0)
            matmuox = tempox;

        }
        else{
            matmuox=10;
           jTextField1.setText((matmuox)+"");
        }
        
        int tempoy=Integer.parseInt(jTextField2.getText());
        if(tempoy>1 && tempoy<25){
            matmuoy = tempoy;
        }
        else{
           matmuoy=10;
           jTextField2.setText((matmuoy)+"");
        }
        
        test = new Labirintas (matmuox,matmuoy);
        int tempid=0;
        for(Langelis[] e : test.getMatmenys()){
            for(Langelis e2 : e){
                e2.setId(tempid);
                tempid++;
           }           
        }
        output.setMatmuox(matmuox);
        output.setMatmuoy(matmuoy);
        taskas = new Taskas(test.getMatmenys());
        taskas.setX(0);
        taskas.setY(0);
        System.out.println("Tasko x: "+taskas.getX());
        System.out.println("Tasko y: "+taskas.getY());
        
        
        langeliai  = new boolean[matmuox*matmuoy];
            for(boolean e: langeliai){
                e=false;
            }
            
        stack = new Stack<>();
       
     
        
        output.setLabirintas(test);
        output.setTaskas(taskas);
        output.repaint();
        
        stack = new Stack<>();
        checkCells=false;
        id=0;
        while(checkCells!=true){
        gretimi = new Langelis[6];  
        gretimuReiksmes = new boolean[6]; 
        nepraeiti = new boolean[6];
        langeliai[id]=true;
        
        gretimi = test.getLangelisPagalID(id).getGretimas();
        gretimuReiksmes = test.getLangelisPagalID(id).getKryptis();
        nepraeitiCount=0;
        
            int i =0;
            for(boolean e: gretimuReiksmes){ //gaunam true tuose i kuriuos yra kryptis
                if(e==false && gretimi[i]!=null){
                    if(langeliai[gretimi[i].getId()]==false){
                nepraeiti[i] =true;
                nepraeitiCount++;
                    }
                }
                else{
                nepraeiti[i]=false;
                }
                i++;
            }
            
            //System.out.println("Nepraeiti count: "+nepraeitiCount);
            int sekancioIndex=0;
            if(nepraeitiCount>0){
                sekancioIndex = ThreadLocalRandom.current().nextInt(1, nepraeitiCount + 1);
                //System.out.println("Atsitiktinis: "+sekancioIndex);// countina tik true, tad random, kuris true, o ne kuris is visu elementu
                i=0;
            for(int j = 0; j<6; j++){
                if(nepraeiti[j]==true){
                i++;
                }
                if(i==sekancioIndex){
                    //System.out.println("Kuris yra tas random: "+j);
                    switch(j){
                        case 0:
                            test.getLangelisPagalID(id).setVK(true);
                            id=test.getLangelisPagalID(id).getGretimas1().getId();
                            stack.push(id);
                            break;
                        case 1:
                            test.getLangelisPagalID(id).setVV(true);
                            id=test.getLangelisPagalID(id).getGretimas2().getId();
                            stack.push(id);
                            break;
                        case 2:
                            test.getLangelisPagalID(id).setVD(true);
                            id=test.getLangelisPagalID(id).getGretimas3().getId();
                            stack.push(id);
                            break;
                        case 3:
                            test.getLangelisPagalID(id).setAD(true);
                            id=test.getLangelisPagalID(id).getGretimas4().getId();
                            stack.push(id);
                            break;
                        case 4:
                            test.getLangelisPagalID(id).setAA(true);
                            id=test.getLangelisPagalID(id).getGretimas5().getId();
                            stack.push(id);
                            break;
                        case 5:
                            test.getLangelisPagalID(id).setAK(true);
                            id=test.getLangelisPagalID(id).getGretimas6().getId();
                            stack.push(id);
                            break;
                        default:
                            break;
                    }
                break;
                }
            }   
            }
            else{
            id=stack.pop();
            }

            for(boolean e: langeliai){ //check ar dar reikia test
                    if(e==false){
                        checkCells=false;
                        break;
                    }
                    else{
                        checkCells=true;
                    }
            }
            for(boolean e: langeliai){ //check ar dar reikia test
                    //System.out.print(e + "  ");
            }
            //System.out.println(" ");
            xxx++;

        }
        
        ilgiausioid = test.paieska(test.getLangelisPagalID(0));
        output.setIlgiausioid(ilgiausioid);
        output.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
     /*int x = taskas.getX();
     int y = taskas.getY();
     System.out.println("Mygtukas");
     
     if(evt.getKeyCode()== KeyEvent.VK_RIGHT){ //right
             x++;
             taskas.setX(x);
     }
     if(evt.getKeyCode()==37){ //left
         x--;
     }
     if(evt.getKeyCode()==38){ //up
         y++;
     }
     if(evt.getKeyCode()==40){ //down
         y--;
     }
     output.repaint();*/
    }//GEN-LAST:event_formKeyTyped

    private void outputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outputKeyPressed

    }//GEN-LAST:event_outputKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    /* int x = taskas.getX();
     int y = taskas.getY();
     System.out.println("Mygtukas");
     
     if(evt.getKeyCode()==KeyEvent.VK_RIGHT){ //right
             x++;
             taskas.setX(x);
     }
     if(evt.getKeyCode()==37){ //left
         x--;
     }
     if(evt.getKeyCode()==38){ //up
         y--;
     }
     if(evt.getKeyCode()==40){ //down
         y++;
     }
     output.repaint();*/
    }//GEN-LAST:event_formKeyPressed

    private void outputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputMousePressed
        try{
        motionTrack = true;
        int x = evt.getX();
        int y = evt.getY();
        

        int tx=0;
        int ty=0;
        
        int tempcheck=0;

        
        gretimi = test.rastiLangeli(taskas.getY(), taskas.getX()).getGretimas();
        gretimuReiksmes = test.rastiLangeli(taskas.getY(), taskas.getX()).getKryptis();
        for(boolean e: gretimuReiksmes){
            //System.out.println("Reiksme: "+e);
        }

        for(Langelis[] e: test.getMatmenys()){
            for(Langelis e2: e){ 
                if(tx%2==0){              
                    if (65+(tx*30) > x && 25+(tx*30) < x && 35+(ty*30) > y && 5+(ty*30) < y){
                        for(Langelis e3: gretimi){ //tikrinu gretimus langelius ar jie ne null
                            if(e3!=null){
                                //System.out.println("vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                if(e3.getY()==tx&&e3.getX()==ty){ //jei gretimas langelis yra tas ant kurio paspausta
                                    if(gretimuReiksmes[tempcheck]==true){ // ir jo reiksme nelygi false
                                        //System.out.println("xxx vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                    taskas.setX(tx);
                                    taskas.setY(ty);
                                    }
                                }
                            }
                            tempcheck++;
                        }
                        //System.out.println("Paspaudimo y koord: "+y + "  y'o koord intervalas nuo:"+(5+(ty*30))+"     iki: "+(35+(ty*30)) );
                    }
                }
                if(tx%2!=0){
                    if (65+(tx*30) > x && 25+(tx*30) < x && 35+15+(ty*30) > y && 5+15+(ty*30) < y){
                        for(Langelis e3: gretimi){
                            if(e3!=null){
                                //System.out.println("vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                if(e3.getY()==tx&&e3.getX()==ty){
                                    if(gretimuReiksmes[tempcheck]==true){
                                        //System.out.println("xxx vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                    taskas.setX(tx);
                                    taskas.setY(ty);
                                    }
                                }
                            }
                            tempcheck++;
                        }
                        //System.out.println("Paspaudimo y koord: "+y + "  y'o koord intervalas nuo:"+(20+(ty*30))+"     iki: "+(50+(ty*30)) );
                    }
                }
                tx++;
            }
            tx=0;
            ty++;
        }
        if(taskas.getY()*matmuox+taskas.getX()==ilgiausioid){
        jDialog1.setVisible(true);
        }
            
        output.repaint();
        }catch(Exception e){
            System.out.println("Out of bounds ar dar koks velnias - click");
        }
    }//GEN-LAST:event_outputMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void outputMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputMouseDragged
        try{
        int x = evt.getX();
        int y = evt.getY();
        
        
        int tx=0;
        int ty=0;
        
        int tempcheck=0;

        
        gretimi = test.rastiLangeli(taskas.getY(), taskas.getX()).getGretimas();
        gretimuReiksmes = test.rastiLangeli(taskas.getY(), taskas.getX()).getKryptis();
        for(boolean e: gretimuReiksmes){
            //System.out.println("Reiksme: "+e);
        }

        for(Langelis[] e: test.getMatmenys()){
            for(Langelis e2: e){ 
                if(tx%2==0){              
                    if (65+(tx*30) > x && 25+(tx*30) < x && 35+(ty*30) > y && 5+(ty*30) < y){
                        for(Langelis e3: gretimi){ //tikrinu gretimus langelius ar jie ne null
                            if(e3!=null){
                                //System.out.println("vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                if(e3.getY()==tx&&e3.getX()==ty){ //jei gretimas langelis yra tas ant kurio paspausta
                                    if(gretimuReiksmes[tempcheck]==true){ // ir jo reiksme nelygi false
                                        //System.out.println("xxx vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                    taskas.setX(tx);
                                    taskas.setY(ty);
                                    }
                                }
                            }
                            tempcheck++;
                        }
                        //System.out.println("Paspaudimo y koord: "+y + "  y'o koord intervalas nuo:"+(5+(ty*30))+"     iki: "+(35+(ty*30)) );
                    }
                }
                if(tx%2!=0){
                    if (65+(tx*30) > x && 25+(tx*30) < x && 35+15+(ty*30) > y && 5+15+(ty*30) < y){
                        for(Langelis e3: gretimi){
                            if(e3!=null){
                                //System.out.println("vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                if(e3.getY()==tx&&e3.getX()==ty){
                                    if(gretimuReiksmes[tempcheck]==true){
                                        //System.out.println("xxx vieta masyve: "+tempcheck + "reiksme masyve"+gretimuReiksmes[tempcheck]);
                                    taskas.setX(tx);
                                    taskas.setY(ty);
                                    }
                                }
                            }
                            tempcheck++;
                        }
                        //System.out.println("Paspaudimo y koord: "+y + "  y'o koord intervalas nuo:"+(20+(ty*30))+"     iki: "+(50+(ty*30)) );
                    }
                }
                tx++;
            }
            tx=0;
            ty++;
        }
        if(taskas.getY()*matmuox+taskas.getX()==ilgiausioid){
        jDialog1.setVisible(true);
        }
            
        output.repaint();
        }catch(Exception e){
        System.out.println("Out of bounds ar dar koks velnias - drag");
        }
    }//GEN-LAST:event_outputMouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(test!=null){
            printComponent(output);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        saveImage("test"+saveCount,"jpg");
        saveCount++;
    }//GEN-LAST:event_jButton4ActionPerformed

    public void printComponent(Component component){
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");

        pj.setPrintable (new Printable() {    
          public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
            return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            component.paint(g2);
            return Printable.PAGE_EXISTS;
          }
        });
        if (pj.printDialog() == false)
        return;

        try {
              pj.print();
        } catch (PrinterException ex) {
              // handle exception
        }
      }
    
    public void saveImage(String name,String type) {
                BufferedImage images = new BufferedImage(output.getHeight()-10, output.getWidth(), BufferedImage.TYPE_INT_RGB);
                Graphics2D gg = images.createGraphics();
                try {
                    gg.translate(0, 0);  // start point of region negated
                    output.paint(gg);
                } finally {
                    gg.dispose();
                }

		try{
			ImageIO.write(images, type, new File(name+"."+type));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private interfacePanel.LabirintasPanel output;
    // End of variables declaration//GEN-END:variables
}
